/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersMeRouteImport } from './routes/_authenticated/users.me'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users.$userId'
import { Route as AuthenticatedChatsChatIdRouteImport } from './routes/_authenticated/chats.$chatId'
import { Route as AuthenticatedUsersMeEditRouteImport } from './routes/_authenticated/users.me_.edit'
import { Route as AuthenticatedChatsUserUserIdRouteImport } from './routes/_authenticated/chats.user.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersMeRoute = AuthenticatedUsersMeRouteImport.update({
  id: '/users/me',
  path: '/users/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatsChatIdRoute =
  AuthenticatedChatsChatIdRouteImport.update({
    id: '/chats/$chatId',
    path: '/chats/$chatId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersMeEditRoute =
  AuthenticatedUsersMeEditRouteImport.update({
    id: '/users/me_/edit',
    path: '/users/me/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatsUserUserIdRoute =
  AuthenticatedChatsUserUserIdRouteImport.update({
    id: '/chats/user/$userId',
    path: '/chats/user/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/chats/$chatId': typeof AuthenticatedChatsChatIdRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/me': typeof AuthenticatedUsersMeRoute
  '/chats/user/$userId': typeof AuthenticatedChatsUserUserIdRoute
  '/users/me/edit': typeof AuthenticatedUsersMeEditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/chats/$chatId': typeof AuthenticatedChatsChatIdRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/me': typeof AuthenticatedUsersMeRoute
  '/chats/user/$userId': typeof AuthenticatedChatsUserUserIdRoute
  '/users/me/edit': typeof AuthenticatedUsersMeEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/chats/$chatId': typeof AuthenticatedChatsChatIdRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/users/me': typeof AuthenticatedUsersMeRoute
  '/_authenticated/chats/user/$userId': typeof AuthenticatedChatsUserUserIdRoute
  '/_authenticated/users/me_/edit': typeof AuthenticatedUsersMeEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chats/$chatId'
    | '/users/$userId'
    | '/users/me'
    | '/chats/user/$userId'
    | '/users/me/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/chats/$chatId'
    | '/users/$userId'
    | '/users/me'
    | '/chats/user/$userId'
    | '/users/me/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/_authenticated/chats/$chatId'
    | '/_authenticated/users/$userId'
    | '/_authenticated/users/me'
    | '/_authenticated/chats/user/$userId'
    | '/_authenticated/users/me_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/me': {
      id: '/_authenticated/users/me'
      path: '/users/me'
      fullPath: '/users/me'
      preLoaderRoute: typeof AuthenticatedUsersMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chats/$chatId': {
      id: '/_authenticated/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AuthenticatedChatsChatIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/me_/edit': {
      id: '/_authenticated/users/me_/edit'
      path: '/users/me/edit'
      fullPath: '/users/me/edit'
      preLoaderRoute: typeof AuthenticatedUsersMeEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chats/user/$userId': {
      id: '/_authenticated/chats/user/$userId'
      path: '/chats/user/$userId'
      fullPath: '/chats/user/$userId'
      preLoaderRoute: typeof AuthenticatedChatsUserUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChatsChatIdRoute: typeof AuthenticatedChatsChatIdRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersMeRoute: typeof AuthenticatedUsersMeRoute
  AuthenticatedChatsUserUserIdRoute: typeof AuthenticatedChatsUserUserIdRoute
  AuthenticatedUsersMeEditRoute: typeof AuthenticatedUsersMeEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChatsChatIdRoute: AuthenticatedChatsChatIdRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersMeRoute: AuthenticatedUsersMeRoute,
  AuthenticatedChatsUserUserIdRoute: AuthenticatedChatsUserUserIdRoute,
  AuthenticatedUsersMeEditRoute: AuthenticatedUsersMeEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
